// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjrdillreulrmtdtwnth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcmRpbGxyZXVscm10ZHR3bnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODE1NzgsImV4cCI6MjA3MzU1NzU3OH0.dVE0ZPNoxayjR8q--_j_Jj8oIrHDt4ogOLIIWEmuo_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});